language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install codecov
env:
  - SH=bash
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export PYTHONPATH=$PYTHONPATH:$(pwd/media_etl)
before_script:
  - sudo psql -c "CREATE ROLE run_admin_run WITH SUPERUSER CREATEDB LOGIN ENCRYPTED PASSWORD 'run_pass_run';" -U postgres
  - psql -c "CREATE DATABASE media_db WITH ENCODING='UTF8' OWNER=run_admin_run CONNECTION LIMIT=24;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE media_db to run_admin_run;" -U postgres
services:
  - postgresql
script:
  - python ./media_etl/postgres_etl.py --port_num=5432
  - python -m pytest
branches:
  only:
   - master
