language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov
env:
  - SH=bash
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export PYTHONPATH=$PYTHONPATH:$(pwd/media_etl)
before_script:
  - psql -c "CREATE DATABASE media_db;" -U postgres
  - psql -c "CREATE USER run_admin_run WITH PASSWORD 'run_pass_run';" -U postgres
services:
  - postgresql
script:
  - python ./media_etl/postgres_etl.py --port_num=5432
  - python -m pytest
branches:
  only:
   - master
